# Introduction to NumPy Arrays

Why do we need NumPy?\
We already have lists.\
numbers = [10, 20, 30, 40, 50]

Looks fine, right?\
For small data: List works.\
For huge data: List becomes slow.
        
* 5 numbers      → Easy\
* 500 numbers    → Easy\
* 50,000 numbers → Slow\
* 5 million      → Very Slow\

Scientists and data analysts need something faster.\
That's why NumPy was created.

## What is NumPy?


NumPy means "Numerical Python"\
It is a library specially designed for:

Mathematics\
Statistics\
Data Analysis\
Machine Learning\
Deep Learning\

Almost every Data Science tool uses NumPy underneath.

## Installation

In [1]:
import numpy as np

Nothing else needed.

### Why "np"?

Instead of writing "import numpy"\
people write "import numpy as np"

This is the worldwide convention.

### First NumPy Array

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)

[10 20 30 40]


Notice:\
No commas are shown. That's normal.

### List vs Array

In [3]:
#Python List:

numbers = [10, 20, 30]

In [4]:
#NumPy Array:

arr = np.array([10, 20, 30])

Looks similar. But NumPy is much faster.

### NumPy is faster than Python lists?

Because it utilizes dense, contiguous, typed memory blocks executed via compiled C code, completely bypassing Python's heavy looping and object-checking overhead.

However, NumPy can become significantly slower than lists when performing element-by-element operations or managing small datasets due to fixed overhead of converting data between the C and python layers.

### What Type Is It?

In [5]:
import numpy as np

arr = np.array([10, 20, 30])

print(type(arr))

<class 'numpy.ndarray'>


Meaning: ndarray = N-dimensional array

Remember this name.

### Access Elements

Exactly like lists.

In [10]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr[0])

10


In [8]:
print(arr[2])

30


### Negative Indexing

In [9]:
print(arr[-1])

40


last element

### Array Size

In [12]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr.size)

4


### Array Shape

In [13]:
print(arr.shape)

(4,)


Meaning:

4 elements\
1 dimension

### Array Data Type

In [15]:
print(arr.dtype)

int32


or int64 (depending on system.)

### Create Array with Zeros

In [16]:
import numpy as np

arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


### Create Array with Ones

In [17]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


### Create Sequential Numbers

In [18]:
arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Understanding arange()

In [20]:
# np.arange(start, stop)
np.arange(1, 6)

array([1, 2, 3, 4, 5])

Notice: stop value not included

### Step Size

In [21]:
arr = np.arange(0, 11, 2)

print(arr)

[ 0  2  4  6  8 10]


### Create Decimal Numbers

In [22]:
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


### What Does linspace Mean?

np.linspace(start, stop, count)\
Means:Create equally spaced numbers

### Random Numbers

In [26]:
import numpy as np

arr = np.random.rand(5)

print(arr)

[0.38947634 0.28870539 0.76280598 0.98717746 0.1820277 ]


Every run is different.

### Simple Math with Arrays

This is where NumPy becomes powerful.

List:

In [29]:
numbers = [1,2,3]

#If we do:

numbers * 2

[1, 2, 3, 1, 2, 3]

Not multiplication!

### NumPy Array

In [31]:
arr = np.array([1,2,3])

print(arr * 2)

[2 4 6]


Real multiplication.

### Addition

In [32]:
arr = np.array([1,2,3])

print(arr + 5)

[6 7 8]


NumPy adds 5 to every element.

### Practice 1

Print:\
array\
size\
shape\
dtype

In [37]:
import numpy as np

arr = np.array([5,10,15,20])

print("array:", arr)
print("size:", arr.size)
print("shape:", arr.shape)
print("dtype:", arr.dtype)

array: [ 5 10 15 20]
size: 4
shape: (4,)
dtype: int32


### Practice 2

Create: np.arange(1, 21)

Expected:[1 2 3 ... 20]

In [38]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Practice 3

Create even numbers:

In [39]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Mini Project — Student Marks Analysis

In [43]:
import numpy as np

marks = np.array([80, 65, 90, 75, 85])

print("Marks:", marks)

print("Total Students:", marks.size)

print("Average Marks:", marks.mean())

print("Highest Marks:", marks.max())

print("Lowest Marks:", marks.min())

Marks: [80 65 90 75 85]
Total Students: 5
Average Marks: 79.0
Highest Marks: 90
Lowest Marks: 65
