# Array Operations

Before NumPy, if you wanted to add 10 to every number:

In [1]:
marks = [50, 60, 70]

new_marks = []

for mark in marks:
    new_marks.append(mark + 10)

print(new_marks)

[60, 70, 80]


Lots of work.

NumPy can do it in one line.

Imagine a classroom:

Student Marks

50, 60, 70

Teacher says 'Add 10 bonus marks to everyone'.

Instead of updating one by one:\
50 → 60\
60 → 70\
70 → 80

NumPy updates everyone together.

## Create an Array

In [2]:
import numpy as np

marks = np.array([50, 60, 70])

print(marks)

[50 60 70]


## Add a Number to Entire Array

In [3]:
marks = np.array([50,60,70])

print(marks + 10)

[60 70 80]


Every element gets +10.

## Subtract a Number

In [4]:
marks = np.array([50,60,70])

print(marks - 5)

[45 55 65]


## Multiply a Number

In [6]:
marks = np.array([50,60,70])

print(marks * 2)

[100 120 140]


## Divide a Number

In [7]:
marks = np.array([50,60,70])

print(marks / 10)

[5. 6. 7.]


Python List: [1,2,3] * 2

Output: [1,2,3,1,2,3]

Not multiplication.

In [8]:
np.array([1,2,3]) * 2

array([2, 4, 6])

## Array + Array

In [11]:
# Suppose two students have marks from two tests.

test1 = np.array([50,60,70])

test2 = np.array([10,20,30])

# Add them

print(test1 + test2)

[ 60  80 100]


## Subtract Arrays

In [14]:
a = np.array([100,200,300])

b = np.array([10,20,30])

print(a - b)

[ 90 180 270]


## Multiply Arrays

In [15]:
a = np.array([1,2,3])

b = np.array([10,20,30])

print(a * b)

[10 40 90]


## Divide Arrays

In [16]:
a = np.array([100,200,300])

b = np.array([10,20,30])

print(a / b)

[10. 10. 10.]


## Power Operation

In [17]:
arr = np.array([2,3,4])

print(arr ** 2)

[ 4  9 16]


## Square Root

In [18]:
arr = np.array([4,9,16,25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


## Sum of All Elements

In [21]:
marks = np.array([50,60,70])

print(marks.sum())

180


## Average

In [23]:
print(marks.mean())

60.0


## Maximum Value

In [26]:
print(marks.max())

70


## Minimum Value

In [29]:
print(marks.min())

50


### Practice 1

In [31]:
import numpy as np

arr = np.array([10,20,30])

print(arr + 5)

[15 25 35]


### Practice 2

In [33]:
arr = np.array([5,10,15])
print(arr * 3)

[15 30 45]


### Practice 3

In [34]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a + b)

[5 7 9]


### Practice 4

In [36]:
arr = np.array([2,3,4])

print(arr ** 2)

[ 4  9 16]


### Practice 5

In [40]:
arr = np.array([10,20,30,40])

print(arr.sum(), arr.mean(), arr.max(), arr.min())

100 25.0 40 10


## Mini Project 
Student Marks Analysis

In [43]:
import numpy as np

marks = np.array([78,85,92,67,88])

print("Marks:")
print(marks)

print("\nTotal Marks:")
print(marks.sum())

print("\nAverage:")
print(marks.mean())

print("\nHighest:")
print(marks.max())

print("\nLowest:")
print(marks.min())

print("\nBonus +5 Marks:")
print(marks + 5)

Marks:
[78 85 92 67 88]

Total Marks:
410

Average:
82.0

Highest:
92

Lowest:
67

Bonus +5 Marks:
[83 90 97 72 93]


In [44]:
salary = np.array([30000,40000,50000])

#Increase salary by 10%

salary * 1.10

array([33000., 44000., 55000.])

## Concepts of Day 21

Array + Number \
Array - Number \
Array * Number \
Array / Number

Array + Array \
Array - Array \
Array * Array \
Array / Array

sum() \
mean() \
max() \
min()

sqrt() \
power (**)