# NumPy Statistics Function

Statistics = Understanding data using numbers

Example:

If a teacher has marks of 100 students, statistics helps answer:
* What is the average mark?
* Who scored highest?
* Who scored lowest?
* How spread out are the marks?

## Dataset

We'll use:

In [3]:
import numpy as np

marks = np.array([80, 90, 70, 85, 95])

Student Marks

80 \
90 \
70 \
85 \
95

## Mean (Average)

The most common statistic.

Formula:   Mean =  Sum of all values / Number of values
    
Example

In [5]:
print(marks.mean())

84.0


Manual Check \
80 + 90 + 70 + 85 + 95 = 420 \
420 ÷ 5 = 84 

Average = 84

## Sum

In [6]:
print(marks.sum())

420


Meaning: Total marks of all students

## Maximum Value

Highest score.

In [7]:
print(marks.max())

95


## Minimum Value

Lowest score.

In [8]:
print(marks.min())

70


## Range

Range means: Highest - Lowest

Formula: Range = Maximum − Minimum

Example:

In [9]:
marks.max() - marks.min()

25

## Median

Median = Middle value after sorting.

Example:

In [11]:
marks = np.array([80,90,70,85,95])
np.median(marks)

85.0

## Why Median Matters

Suppose salaries:

In [12]:
salaries = np.array([20000,25000,30000,35000,500000])

Average becomes very high because of one rich person.

Median gives a better picture of a "typical" salary.

Data scientists use median a lot.

## Standard Deviation (Easy Version)

Imagine two classes:

Class A: 50 51 49 50 50

Class B: 10 50 90 20 80

Both may have similar averages.

But:

Class A → Students are close together

Class B → Students are far apart

Standard deviation measures spread.

Code:

In [13]:
marks.std()

8.602325267042627

### Easy Rule

Small Std → Data close together

Large Std → Data spread out

## Variance

Variance is related to standard deviation.

Formula: Standard Deviation=  under root (Variance)

Code:

In [14]:
marks.var()

74.0

## Sorting Data

In [16]:
np.sort(marks)

array([70, 80, 85, 90, 95])

## Find Index of Maximum

In [17]:
marks.argmax()

4

Largest value is at position 4

## Find Index of Minimum

In [18]:
marks.argmin()

2

## Count Values

In [19]:
len(marks)

5

In [20]:
marks.size

5

## Statistics on 2D Arrays

Dataset:

In [21]:
students = np.array([
    [80,90],
    [70,85],
    [95,88]
])

## Overall Average

In [22]:
students.mean()

84.66666666666667

## Average of Each Column

In [24]:
students.mean(axis=0)

array([81.66666667, 87.66666667])

Math Average \
Science Average

## Average of Each Row

In [25]:
students.mean(axis=1)

array([85. , 77.5, 91.5])

Student 1 Average \
Student 2 Average \
Student 3 Average

## Understanding Axis

Remember:

axis=0 \
↓ \
Go Down \
Columns 

axis=1 \
→ \
Go Across \
Rows

### Practice 1
import numpy as np

marks = np.array([50,60,70,80,90])

Find:

marks.sum() \
marks.mean() \
marks.max() \
marks.min() 

Expected:

350 \
70 \
90 \
50

In [37]:
import numpy as np

marks = np.array([50,60,70,80,90])

print(marks.sum(), marks.mean(), marks.max(), marks.min())

350 70.0 90 50


### Practice 2

Find: np.median(marks)

Expected: 70

In [38]:
np.median(marks)

70.0

### Practice 3

Find: np.sort(marks)

Expected: [50 60 70 80 90]

In [40]:
np.sort(marks)

array([50, 60, 70, 80, 90])

### Practice 4

Find:
marks.argmax()\
marks.argmin()

Expected: 4 0

In [42]:
print(marks.argmax(), 
marks.argmin())

4 0


### Practice 5

Create:

data = np.array([ \
    [10,20], \
    [30,40], \
    [50,60] \
])

Find:

data.mean() \
data.mean(axis=0) \
data.mean(axis=1)

In [44]:
data = np.array([
    [10,20],
    [30,40],
    [50,60]
])

print("Mean: ", data.mean())
print("Column: ",data.mean(axis=0))
print("Row: ",data.mean(axis=1))

Mean:  35.0
Column:  [30. 40.]
Row:  [15. 35. 55.]


## Mini Project 

Exam Result Analysis

In [31]:
import numpy as np

marks = np.array([78,85,92,67,88,74,95])

print("Marks:", marks)

print("\nTotal:", marks.sum())

print("\nAverage:", marks.mean())

print("\nHighest:", marks.max())

print("\nLowest:", marks.min())

print("\nMedian:", np.median(marks))

print("\nStandard Deviation:", marks.std())

print("\nSorted Marks:", np.sort(marks))

Marks: [78 85 92 67 88 74 95]

Total: 579

Average: 82.71428571428571

Highest: 95

Lowest: 67

Median: 85.0

Standard Deviation: 9.376479475098252

Sorted Marks: [67 74 78 85 88 92 95]


Notes

* mean()
* median()
* max()
* min()
* range
* std()
* var()
* argmax()
* argmin()
* sort()