# NumPy Reshaping Arrays

We'll learn how to change the shape of data without changing the data itself.

Think of LEGO blocks.

We have 6 blocks: 1 2 3 4 5 6

We can arrange them as:

1 2 3 \
4 5 6

or

1 2 \
3 4 \
5 6

Same blocks.

Different arrangement.

That's exactly what reshape() does.

## What is Reshaping?

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr)

[1 2 3 4 5 6]


In [2]:
print(arr.shape)

(6,)


Meaning

1 Row \
6 Elements

## Reshape into 2 Rows and 3 Columns

In [4]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [5]:
print(new_arr.shape)

(2, 3)


Before:

1 2 3 4 5 6

After:

1 2 3 \
4 5 6

### Another Example

In [6]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(3,2)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


Shape: (3,2)

### Important Rule

Total elements must stay the same.

We have: 6 elements

Possible shapes:

2 × 3 = 6 ✅

3 × 2 = 6 ✅

1 × 6 = 6 ✅

6 × 1 = 6 ✅

Not possible:

4 × 2 = 8 ❌

### Error Example

In [7]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

Because Need 8 values Have only 6 values

## Reshape into 1 Row

In [8]:
arr = np.array([1,2,3,4])

new_arr = arr.reshape(1,4)

print(new_arr)

[[1 2 3 4]]


## Reshape into 1 Column

In [10]:
arr = np.array([1,2,3,4])

new_arr = arr.reshape(4,1)

print(new_arr)

[[1]
 [2]
 [3]
 [4]]


## Why Column Shape Matters?

Machine Learning often expects:

Age \
25 \
30 \
35 \
40

instead of: 25 30 35 40

So we'll frequently see:

In [ ]:
ages.reshape(-1,1)

## Using -1 (Automatic Calculation)

NumPy can calculate one dimension for us.

In [15]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,-1)

print(new_arr)

[[1 2 3]
 [4 5 6]]


NumPy thinks:

2 Rows

Need total 6 elements

Columns = 3

### Example

In [20]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(-1,2)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


NumPy calculates rows automatically.

## Flatten a 2D Array

In [21]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

In [22]:
#Convert back to 1D

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


In [24]:
# Example

students = np.array([
    [80,90],
    [70,85],
    [95,88]
])

students.shape

(3, 2)

3 Students \
2 Subjects

This is exactly how datasets are stored.

## Practice 1

In [29]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


## Practice 2

In [30]:
new_arr = arr.reshape(-1,2)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


## Practice 3

In [31]:
arr = np.array([10,20,30,40])

new_arr = arr.reshape(4,1)

print(new_arr)

[[10]
 [20]
 [30]
 [40]]


## Practice 4

In [33]:
new_arr = arr.reshape(2,-1)

print(new_arr)

[[10 20]
 [30 40]]


## Practice 5

In [35]:
flat = arr.flatten()

print(flat)

[10 20 30 40]


## Mini Project 

Student Dataset

In [1]:
import numpy as np

marks = np.array([80,90,70,85,95,88])

students = marks.reshape(3,2)

print("Dataset:")
print(students)


print("\nShape:")
print(students.shape)

print("\nFlatten:")
print(students.flatten())

Dataset:
[[80 90]
 [70 85]
 [95 88]]

Shape:
(3, 2)

Flatten:
[80 90 70 85 95 88]
