# 2D NumPy Arrays (Rows & Columns)

Today is a big milestone because we move from:

[10, 20, 30, 40]

to something that looks like an Excel sheet:

[
 [10, 20, 30], \
 [40, 50, 60], \
 [70, 80, 90] \
]

This is how real datasets are stored.

## First Understand 1D vs 2D

### 1D Array

Like a single line of students.

arr = np.array([10,20,30,40])

Visual:

10 20 30 40

### 2D Array

Like a classroom.

arr = np.array([ \
    [10,20,30], \
    [40,50,60], \
    [70,80,90]  \
])

Visual:

10 20 30 \
40 50 60 \
70 80 90 

Rows and columns.

## Creating our First 2D Array

In [2]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


### Shape

In [4]:
print(arr.shape)

(3, 3)


Meaning: (3 Rows, 3 Columns)

### Example

In [5]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(arr.shape)

(2, 4)


2 Rows, 4 Columns

### Size

In [8]:
print(arr.size)

8


Because 2 × 4 = 8 elements

### Dimensions

In [10]:
print(arr.ndim)

2


2D Array

## Accessing Elements

Suppose:

In [11]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

Syntax \
arr[row, column]

Remember: \
Rows first \
Columns second

### First Element

In [12]:
print(arr[0,0])

10


In [13]:
print(arr[0,1])

20


### Middle Element

In [14]:
print(arr[1,1])

50


Last Element

In [16]:
print(arr[2,2])

90


In [17]:
arr[1,2]

60

### Entire Row

Get first row:

In [19]:
print(arr[0])

[10 20 30]


Second row

In [20]:
print(arr[1])

[40 50 60]


In [22]:
print(arr[2])

[70 80 90]


### Entire Column

Get first column:

In [24]:
print(arr[:,0])

[10 40 70]


What does : mean

:  = Everything

In [26]:
arr[:,0]

array([10, 40, 70])

All rows, Column 0

Second Column

In [28]:
print(arr[:,1])

[20 50 80]


### Row Slicing

First two rows:

In [29]:
print(arr[0:2])

[[10 20 30]
 [40 50 60]]


### Column Slicing

First two columns:

In [32]:
print(arr[:,0:2])

[[10 20]
 [40 50]
 [70 80]]


### Modify Elements

In [34]:
arr[0,0] = 999

print(arr)

[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]


## Create Matrix of Zeros

In [36]:
arr = np.zeros((3,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Create Matrix of Ones

In [39]:
arr = np.ones((2,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


### Example

Student data:

In [40]:
students = np.array([
    [101,80],
    [102,90],
    [103,70]
])

#Get all IDs

print(students[:,0])

[101 102 103]


In [41]:
#Get all marks:

print(students[:,1])

[80 90 70]


This is exactly how machine learning datasets work.

### Practice 1

In [43]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 3)
9
2


In [44]:
print(arr[0,0])
print(arr[1,1])
print(arr[2,2])

1
5
9


## Mini Project — Student Marks Dataset

In [46]:
import numpy as np

students = np.array([
    [101,80],
    [102,95],
    [103,70],
    [104,88]
])

print("Dataset:")
print(students)

print("\nStudent IDs:")
print(students[:,0])

print("\nMarks:")
print(students[:,1])

print("\nHighest Marks:")
print(students[:,1].max())

Dataset:
[[101  80]
 [102  95]
 [103  70]
 [104  88]]

Student IDs:
[101 102 103 104]

Marks:
[80 95 70 88]

Highest Marks:
95
