# NumPy Indexing & Slicing

Data = A big book

Indexing = Read one page

Slicing = Read several pages

Day 18 We created arrays:

import numpy as np \
arr = np.array([10, 20, 30, 40, 50])

Output: [10 20 30 40 50]

Today we'll learn how to pick data from this array.

## Part 1: Indexing

Index means position.

Array

[10 20 30 40 50]

 0  1  2  3  4

In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

#First Element
print(arr[0])

#Second Element
print(arr[1])

#Third Element
print(arr[2])

10
20
30


### Negative Indexing

Python can count from the end.

[10 20 30 40 50]

-5 -4 -3 -2 -1

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


In [8]:
print(arr[-2])

40


## Part 2: Slicing

Syntax:      arr[start:end]

Remember:
Start Included \
End Excluded 

In [9]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[1:4])

[20 30 40]


Why?

Position 1 → Included \
Position 4 → Excluded

In [10]:
print(arr[0:3])

[10 20 30]


In [11]:
print(arr[2:6])

[30 40 50 60]


### Beginning to End

In [13]:
print(arr[:4])    #Python assumes: arr[0:4]

[10 20 30 40]


### Middle to End

In [16]:
print(arr[3:])    #Python assumes: arr[3:last]

[40 50 60 70]


### Entire Array

In [18]:
print(arr[:])

[10 20 30 40 50 60 70]


### Step Size

Syntax:

arr[start:end:step]

In [19]:
#Every Second Number

print(arr[::2])

[10 30 50 70]


Explanation:

Take 1 \
Skip 1 \
Take 1 \
Skip 1

In [22]:
# Every Third Number
print(arr[::3])

[10 40 70]


### Reverse Array

In [24]:
print(arr[::-1])

[70 60 50 40 30 20 10]


### Modify Elements

NumPy arrays are mutable.

In [25]:
#Change One Value

arr = np.array([10,20,30,40])

arr[1] = 99

print(arr)

[10 99 30 40]


In [26]:
#Change Multiple Values

arr[1:4] = 100

print(arr)

[ 10 100 100 100]


NumPy updates multiple values at once.

### Fancy Indexing

In [28]:
# Select multiple positions.

arr = np.array([10,20,30,40,50])

print(arr[[0,2,4]])

[10 30 50]


### Boolean Indexing

In [29]:
marks = np.array([35,80,45,90,20])

#Get only passing marks.

print(marks > 40)

[False  True  True  True False]


In [30]:
print(marks[marks > 40])

[80 45 90]


Example

In [31]:
ages = np.array([12,18,25,14,30,16,40])

print(ages[ages >= 18])

[18 25 30 40]


This is exactly how data cleaning works.

Practice 1

In [46]:
import numpy as np

arr = np.array([5,10,15,20,25])

print(arr[0], arr[2], arr[-1])

5 15 25


Practice 2

In [48]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])

[20 30 40]


Practice 3

In [49]:
print(arr[::-1])

[60 50 40 30 20 10]


Practice 4

In [51]:
marks = np.array([25,40,55,80,35])

#Print only marks greater than 40.
print(marks[marks > 40])

[55 80]


Practice 5

In [53]:
numbers = np.array([1,2,3,4,5,6,7,8])

print(numbers[::2])

[1 3 5 7]


## Mini Project — Student Marks Filter

In [55]:
import numpy as np

marks = np.array([35, 80, 60, 25, 95, 45])

print("All Marks:")
print(marks)

passed = marks[marks >= 40]

print("\nPassed Students:")
print(passed)

print("\nNumber Passed:")
print(len(passed))

All Marks:
[35 80 60 25 95 45]

Passed Students:
[80 60 95 45]

Number Passed:
4
